name: 'release'
on:
  push:
    branches:
      - 'main'
jobs:
  main:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: pinnacles/github-action-module-release/.github/actions/release-by-merge@v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
