name: Validate PR Title
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: pinnacles/github-action-module-release/.github/actions/validate-pr-title@v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
